Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,21 +16,26 @@ jobs:
         run: |
           mkdir -p veracode-cli
           curl -fsSLo veracode-cli/veracode.zip https://downloads.veracode.com/tools/cli/latest/veracode-cli.zip
-          unzip veracode-cli/veracode.zip -d veracode-cli
+          
+          # Verify if download was successful
+          if [ ! -s veracode-cli/veracode.zip ]; then
+            echo "Veracode CLI download failed. Exiting."
+            exit 1
+          fi
+
+          # Unzip the Veracode CLI and add it to PATH
+          unzip veracode-cli/veracode.zip -d veracode-cli || { echo "Unzipping failed"; exit 1; }
           export PATH=$PATH:$PWD/veracode-cli
           echo "Veracode CLI installed in $(pwd)/veracode-cli"
 
       - name: Verify Veracode CLI Installation
-        run: |
-          veracode --version
+        run: veracode --version
 
       - name: Configure Veracode CLI
-        run: |
-          veracode configure --api-id ${{ secrets.VERACODE_API_ID }} --api-key ${{ secrets.VERACODE_API_KEY }}
+        run: veracode configure --api-id ${{ secrets.VERACODE_API_ID }} --api-key ${{ secrets.VERACODE_API_KEY }}
 
       - name: Package Application with Veracode Auto-Packager
-        run: |
-          veracode auto-package --type directory --source ${{ github.workspace }} --output ${{ github.workspace }}/veracode_package.zip
+        run: veracode auto-package --type directory --source ${{ github.workspace }} --output ${{ github.workspace }}/veracode_package.zip
 
       - name: Upload and Scan
         run: |
